import groovy.transform.Field

library 'jenkins-tutorial-shared-lib'

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'super-report-printer'

pipeline {
    // We should really use some specific agent, we are getting crashes on some agents without Node or Docker!
    agent {
        kubernetes {
            inheritFrom 'Node16Alpine Kaniko'
            defaultContainer 'node16'
            yamlMergeStrategy merge()
            yaml '''
            spec:
              containers:
                - name: python
                  image: python:3.10-alpine3.16
                  command: ["sleep", "infinity"]
                  resources:
                    requests:
                      cpu: 10m
                      memory: 16Mi
                    limits:
                      cpu: 1
                      memory: 16Mi
            '''
        }
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        ansiColor('xterm')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    container('python') {
                        sh './report_generator.py'
                    }
                }
            }
        }

        stage('Install dependencies') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm ci'
                }
            }
        }

        stage('Build Typescript') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm run build'
                }
            }
        }

        stage('Files') {
            steps {
                dir(PROJECT_DIR) {
                    script {
                        def envs = getSecrets()
                        println "${envs}"
                    }
                }
            }
        }
    }
}

def getSecrets() {
    def array = new File(".env.sample") as String[]
    return array
}

def getImageTag() {
    def tags = [sanitizeImageTag("${env.GIT_BRANCH}-${env.GIT_COMMIT}")]
    if (isMaster()) {
        tags += 'latest'
    }
    return tags
}